services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercado_pago_validador_db
    ports:
      - "3307:3306"
    networks:
      - validador-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

  validador-backend:
    build:
      context: ./validador-backend
      target: production
    container_name: validador-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./validador-backend/.env
    networks:
      - validador-net

  validador-frontend:
    build:
      context: ./validador-frontend
      target: production
    container_name: validador-frontend
    ports:
      - "80:80"
    depends_on:
      - validador-backend
    networks:
      - validador-net

networks:
  validador-net:
    driver: bridge

volumes:
  mysql-data:
