        spring.application.name=validador-backend
        spring.config.import=optional:classpath:application-secret.properties
        server.port=8080

        # Conexión a la base de datos
        spring.datasource.url=${SPRING_DATASOURCE_URL}
        spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
        spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
        spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

        # JPA / Hibernate
        spring.jpa.hibernate.ddl-auto=update
        spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
        spring.jpa.show-sql=false
        logging.level.org.hibernate.SQL=off
        logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off

        # Mercado Pago
        mercadopago.access-token=${MP_ACCESS_TOKEN}

        # OAuth de terceros
        urlCallback=${URL_CALLBACK}
        clientId=${CLIENT_ID}
        clientSecret=${CLIENT_SECRET}

        # Encriptado y JWT
        algoritmoEncriptar=${ENCRYPT_ALGO:AES}
        secretKeyEncriptar=${SECRET_KEY}
        expiration=${JWT_EXPIRATION:86400000}
        token.expiration=${TOKEN_EXPIRATION:604800000}

        # # 🔇 Desactiva el banner ASCII al iniciar la app
        spring.main.banner-mode=off

        # 🔇 Desactiva el log de estadísticas del WebSocket broker
        logging.level.org.springframework.web.socket.config.WebSocketMessageBrokerStats=OFF


        # # 🛑 Desactiva la inyección automática de propiedades por DevTools
        # spring.devtools.add-properties=false

        # # Te muestra un resumen de qué configuraciones se activaron y por qué, para ayudarte a entender cómo se armó el contexto de Spring.
        # spring.conditions.report.enabled=false
        
        # # 🔁 Desactiva el servidor LiveReload (hot reload en navegador)
        # spring.devtools.livereload.enabled=false

        # # 🧠 Desactiva el modo "open-in-view" de JPA (evita consultas en fase de renderizado web)
        # spring.jpa.open-in-view=false

        # # 🧹 Reduce el nivel de logs de Hibernate (evita spam de SQL en consola)
        # logging.level.org.hibernate=ERROR

        # # 🧹 Reduce el nivel de logs de Spring Framework
        # logging.level.org.springframework=INFO

        # # 🧹 Reduce el nivel de logs web (controladores, filtros, etc.)
        # logging.level.web=ERROR

        # # 🧹 Reduce el nivel de logs del binder de Hibernate (evita mostrar valores bind en SQL)
        # logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

        # # 🧹 Desactiva el log de dialecto obsoleto (si ya corregiste el dialecto)
        # logging.level.org.hibernate.orm.deprecation=ERROR

        # # 🧹 Desactiva el warning sobre UserDetailsService si estás usando AuthenticationProvider manual
        # logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR