services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercado_pago_validador_db
    ports:
      - "3306:3306"
    networks:
      - validador-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  validador-backend:
    build: .
    container_name: validador-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - validador-net

networks:
  validador-net:
    driver: bridge